### ISSUE TITLE
Model version issues

### ISSUE THREAD

**Issue by YanZongzheng** [MAGALA-RICHARD/apsimNGpy#12]
Which version of APSIMNG are you basing this package on, when I run the .apsimx file with version 2024.7.7548.0 I get tons of errors. eg:
![屏幕截图 2024-08-01 230736](https://github.com/user-attachments/assets/dbc291a6-3ceb-47de-9c23-259dc27be1ac)
The APSIM examples shown in the figure are all in error.
【System.Exception: Error in file:  Simulation: PastureByWaterAndNitrogenNitrogen15Watertrue
 ---> System.Exception: Invalid path: [FertiliseFixedDates].Script.Amount】

**Comment by MAGALA-RICHARD** [comment]
All versions should be able to work according to the newly released version. That error is likely not attributed to the apsimNGPy package, and I suggest you All versions should be compatible with the newly released version. The error is likely not caused by the apsimNGPy package. I recommend checking the file or rerunning with a new file and comparing the differences. I will also verify with the latest version.

**Comment by MAGALA-RICHARD** [comment]
This version works https://registration.apsim.info/?version=2024.05.7493.0&product=APSIM%20Next%20Generation.
released on 05-22-2024 works and many others below it. 

I think you should use the Config Module. You can install different versions and change the path through this module 
```python
from apsimNGpy.config import Config
# print out the current binary path
print(Config.get_aPSim_bin_path())
# If you know the location of any installed APSIM version, you can direct apsimNGpy pythonnet config module to use that path # as shown below
bin_path  = r'path/toapsimbinaries/bin'
Config.set_aPSim_bin_path(bin_path)
# This path should end with the word bin
# please run the script two times after changing due to the cache effect
# After changing to another version, you can now import apsimNGpy modules safely


```
